imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en


framework:
    workflows:
        idea:
            type: 'state_machine'
            marking_store:
                type: 'single_state' # or 'single_state'
                arguments:
                    - 'status'
            supports:
                - AppBundle\Entity\Idea
            places:
                - new
                - considering
                - planned
                - started
                - completed
                - denied
            transitions:
                consider:
                    from: new
                    to: considering
                plan:
                    from: considering
                    to: planned
                start:
                    from: planned
                    to: started
                complete:
                    from: started
                    to: completed
                reopen:
                    from: completed
                    to: new
                reject:
                    from: [new, considering, planned, started, completed]
                    to: denied
                reconsider:
                    from: denied
                    to: new
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_sqlite
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        path:     "%kernel.cache_dir%/database"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

easy_admin:
    entities:
        Idea:
            class: AppBundle\Entity\Idea
            list:
                actions:
                    - {name: 'change_status', type: 'route',  icon: 'plus-square' }
            form:
                fields:
                    - title
                    - description
                    - { property: 'category', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Category' }}
        Category:
            class: AppBundle\Entity\Category
